### ISSUE TITLE
No startup on Mac

### ISSUE THREAD

**Issue by citrusmunch** [MathInspector/MathInspector-Alpha-Test#2]
Launching `mathinspector.app` after unzipping `mathinspector_mac-os.zip` doesn't have any effect.
I've moved to `/Applications/` and even ran ` xattr -d -r com.apple.quarantine /Applications/mathinspector.app/`.

**Comment by MathInspector** [comment]
I looked in to this bug and found out there is an issue with tcl not being packaged with the mac build properly.  I will be uploading a fix which will make it run out of the box as soon as I can, which might take a day or two.  Sorry about that!

Do you have python 3.7 on your machine?  If so, it might be possible to get it working by installing that from the python website, as this should install the tcl dependency.  Let me know if that works and I will reply again when the fix is up.

**Comment by citrusmunch** [comment]
Sounds good!
I do have Python 3.7.6 installed, so it might be something else?
I also tried the same process with the new zip `mathinspector_macos-0.1.1.zip`, no luck.

If it matters, the `python3` I use is from homebrew and is at `/usr/local/bin/python3`.

**Comment by citrusmunch** [comment]
In the directory `/Applications/mathinspector.app/`, running `./Contents/MacOS/mathinspector` gives the error:

```
$ ./Contents/MacOS/mathinspector
Traceback (most recent call last):
  File "mathinspector.py", line 234, in <module>
  File "mathinspector.py", line 31, in __init__
  File "ttkthemes/themed_tk.py", line 41, in __init__
  File "tkinter/__init__.py", line 2023, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    /Applications/mathinspector.app/Contents/MacOS/tclResources /Applications/mathinspector.app/Contents/MacOS/tcl8.6 /Library/Frameworks/Python.framework/Versions/3.7/lib/tcl8.6 /Applications/mathinspector.app/Contents/lib/tcl8.6 /Applications/mathinspector.app/lib/tcl8.6 /Applications/mathinspector.app/Contents/library /Applications/mathinspector.app/library /Applications/mathinspector.app/tcl8.6.8/library /Applications/tcl8.6.8/library



This probably means that Tcl wasn't installed properly.

[88523] Failed to execute script mathinspector
```

Of those searched directories, only `/Applications/mathinspector.app/Contents/MacOS/tclResources/` exists. It has one item `Tcl` and running it gives:

```
$ ./Contents/MacOS/tclResources/Tcl --version
Failed to execute process './Contents/MacOS/tclResources/Tcl'. Reason:
exec: Exec format error
The file './Contents/MacOS/tclResources/Tcl' is marked as an executable but could not be run by the operating system.
```

So maybe still a tcl error ?

**Comment by MathInspector** [comment]
Awesome, thanks for the info, this is very helpful!  I was going to suggest running that file actually.

I think there is a difference between the version of tcl installed when python is installed via homebrew vs the python website, and also may depend on other factors.  I think it might be possible to repackage the mac app with homebrew python and it will correctly include the tcl dependency.  I have been talking to a test user irl who had the same problem and trying to debug it with their assistance, that's how I knew it was a tcl issue.

During development I actually started using homebrew's version of python and switched over to the python website version instead because of a tcl issue.  It was pretty annoying to change between python installs but I am going to try reverting everything to homebrew as the next idea to solve this.  Will keep you posted.

**Comment by MathInspector** [comment]
I just uploaded a new mac build 0.1.2 at the download link which I believe will resolve this issue.  I think I discovered what went wrong and was able to include tcl in a completely different way and then work through a lot of various issues finally got it running.  I really hope it works!

**Comment by citrusmunch** [comment]
Still not opening, but I think it's better than before!

In `/Applications/mathinspector.app/`:

```
$ ./Contents/MacOS/mathinspector

OS-CWD /Applications/mathinspector.app
_MEIPASS /Applications/mathinspector.app/Contents/MacOS
Traceback (most recent call last):
  File "mathinspector.py", line 247, in <module>
  File "mathinspector.py", line 31, in __init__
  File "ttkthemes/themed_tk.py", line 41, in __init__
  File "tkinter/__init__.py", line 2023, in __init__
_tkinter.TclError: Can't find a usable init.tcl in the following directories:
    /Applications/mathinspector.app/Contents/MacOS/tcl /Applications/mathinspector.app/Contents/MacOS/tcl8.6 /Library/Frameworks/Python.framework/Versions/3.7/lib/tcl8.6 /Applications/mathinspector.app/Contents/lib/tcl8.6 /Applications/mathinspector.app/lib/tcl8.6 /Applications/mathinspector.app/Contents/library /Applications/mathinspector.app/library /Applications/mathinspector.app/tcl8.6.8/library /Applications/tcl8.6.8/library

/Applications/mathinspector.app/Contents/MacOS/tcl/init.tcl: version conflict for package "Tcl": have 8.6.8, need exactly 8.5.9
version conflict for package "Tcl": have 8.6.8, need exactly 8.5.9
    while executing
"package require -exact Tcl 8.5.9"
    (file "/Applications/mathinspector.app/Contents/MacOS/tcl/init.tcl" line 19)
    invoked from within
"source /Applications/mathinspector.app/Contents/MacOS/tcl/init.tcl"
    ("uplevel" body line 1)
    invoked from within
"uplevel #0 [list source $tclfile]"


This probably means that Tcl wasn't installed properly.

[898] Failed to execute script mathinspector
```


If I edit `/Applications/mathinspector.app/Contents/MacOS/tcl/init.tcl` line 19 to be `package require -exact Tcl 8.6.8`, I can run math inspector (with some errors) from the shell!

Launching the app by clicking from `/Applications/` still doesn't work, but now it briefly changes the menubar to say "mathinspector File" before crashing (before it wouldn't show any attempt at launching).

**Comment by MathInspector** [comment]
At least you were able to get it working!  Ok thanks for all this info, super helpful.  Going to try and resolve this as soon as I can and will let you know when a new build is up.

**Comment by MathInspector** [comment]
Just uploaded a new build, version 0.1.3, have a feeling this might have done it.

I was able to get the app to open with a double click on my machine by including a new folder 
in the MacOS directory `tcl8` which has the python 3.7 tcl framework for version 8.6.8

**Comment by citrusmunch** [comment]
Yay! I think everything is working!
I've only played around with it a little bit, but no errors so far. 🎉
