### ISSUE TITLE
Open Source

### ISSUE THREAD

**Issue by Thovthe** [MathInspector/MathInspector-Alpha-Test#4]
Hey @MathInspector,

I am really excited about this tool, a mathematical plaything like this is something I've had an eye open for for a while.  I understand you are looking at opensourcing it.  Here's a gentle suggestion about open source development, just open it up and let people poke around in the code while they are testing it.  No one reasonable minds if it might be messy or not quite perfect, you'll probably find out that some developers come by and do small drive-by changes to improve it and others come and stick around in the community that grows around the software.

Check out [this](https://producingoss.com/) excellent (I'm told) opensource book on the subject.

And if you're looking for a place to host discussions I suggest opening a [Matrix](https://matrix.org) room with something like [riot.im](https://riot.im/app).

Wishing you the best of success,
Thovthe

**Comment by MathInspector** [comment]
Hi, thanks for this advice.  I recently have been quite busy, however I want to let you know I have already basically come to this conclusion!

I am planning to do this in 1-3 months, officially release everything, and then go for it.

To be honest, the code is a little messy in some part, and its kind of embarrassing

There are so many ambitious features that its hard to do a big refactor.  I feel very strongly that the code has to be really clean before I open source it, but have been waiting for more feedback from the alpha test before making another move.

I am very strongly taking your advice into consideration, and will likely move to open source much faster than otherwise as a result of you taking the time to share you thoughts on this.

Thanks!

**Comment by MathInspector** [comment]
Ok I thought more about this, I think you are making some really solid points @Thovthe 

This is not a promise, but I will try to have the entire thing open sourced in 4 weeks from now.  I will start working on it today or tomorrow again and clean up the code, stop adding new features, do a big refactor, and get together with my lawyer to make sure I do all the open source stuff correctly and it can never be sold for money no matter what.

Let me know if you have any more advice about this process.  I think the alpha test has run its course and its time to take the next step.  I had considered opening a Patreon for this project, but now I think a better decision is to completely open source everything and then evaluate what to do next based on the feedback of the community and how things develop from there.

I will be in touch in this Issue thread with updates about my progress so anyone who is curious can get the latest news.

**Comment by Thovthe** [comment]
I'm glad to see that you are taking my suggestion in the spirit intended @MathInspector.

> This is not a promise,

Open source is made up of mostly volunteers so it's not expected that you have a deadline ;) As is called out in all-caps in most Open Source licenses, "PARTIES PROVIDE THE PROGRAM "AS IS" WITHOUT WARRANTY OF ANY KIND"

I do have some advice, it is as follows.  If you feel a strong need to refactor beforehand you certainly can but an alternative is describing a plan for the refactor that you and other developers could run with and opening it up as soon as the legal ducks are in a row (you may get help, who knows?).  Regarding the legal side of things, you'll need to select a license, the general advice is to select one of the well know and understood licenses.  [Here](https://arstechnica.com/gadgets/2020/02/how-to-choose-an-open-source-license/) is a somewhat opinionated article that talks about Open Source licenses and copyright.  Further information can be found at the OSI (Open Source Initiative) [website](https://opensource.org/licenses) on licenses.

Now, I see that you've said, "[so that] it can never be sold for money no matter what."  I fully understand that impulse but I think maybe what you really care about is that no company swoops in, takes the impressive foundation you (and eventually others) have built, adds some large or small functionality that makes it more marketable and then proceeds to make oodles of cash which none of the development team get to take part in, it's happened before.  If this is what you worry about I suggest releasing under a copyleft license (more information in the above links).  This kind of license requires that any modifications to the code be made publicly available under the same license as the original work and therefore available to be up-streamed into the original project.  It doesn't curtail people's freedom to charge for a copy of the software but it does effectively hamstring the method by which someone might take over a project like this for profit.

Finally, if you feel like opening a Patreon or providing some other method of donation feel free.  There are options here, do you want it to be about supporting you specifically to work on the project?  Do you want it to go to the community at large, maybe a stipend to possible core developers and other maintainers?  Big questions but you can change much of this over time.  One caution, don't expect it to be a huge amount of money, open source is perennially underfunded a lot of the **people** who care about it aren't super flush and the methods for moving money around are not very low friction.  This software fits the educational bill so you may be able to apply for certain grants but that's down the line I'm sure.

**Comment by Thovthe** [comment]
If you like, I could open a matrix room for the project.

**Comment by MathInspector** [comment]
I think you may have misunderstood me, you said

```
I think maybe what you really care about is that no company swoops in, takes the impressive foundation you (and eventually others) have built, adds some large or small functionality that makes it more marketable and then proceeds to make oodles of cash
```

This is 100% *not* what I am worried about.  This project is a free gift to honor the mathematician Ramanujan and my main goal is to make sure it has wide distribution in India for students who might not have access to the best mathematics software on the Market.  I don't want anyone to be allowed to profit off the code because I want it to be the ultimate math program; the Blender or Gimp of Math Software.

This project was made for people who grew up learning Math from youtube

1. Make it easy to play around and create sample projects for educational math youtube videos
2. Make it easy for young people to make high quality animations for their own math channels

This project is also designed for professional mathematics researchers and scientists.

There is no financial incentive.  However, I have asked my lawyer about setting up a MathInspector Foundation since many open source projects have that.  I don't need the money, this is perhaps my one chance to make a real contribution to science and I am doing everything I can to make sure I can achieve these goals.  I simply don't want another company to ever sell it for money ever period.

I have also moved the timeline from 4 weeks to 1 week.  After thinking about it, its not that bad.  I already did like 4 refactors as I was building it last year.  1 more and its not going to be a huge job, we can work together as a community to get the executables working and run it from the command line.

Please let me know if you have any more feedback or advice.  I really appreciate it so much thank you!

**Comment by Thovthe** [comment]
It's good that you are so committed.  I think a tool to help bring up the next generation of mathematicians from a background different from the traditional training is an excellent tribute to Ramanujan.

GIMP and Blender each use different versions of the GPL, [v3](https://www.gimp.org/about/) and [v2](https://www.blender.org/about/license/) respectively.

Here is a link that can get people to the matrix room, https://matrix.to/#/#MathInspector:matrix.org  I took the liberty of using the mandala from the website and this github as the picture for the room but let me know if that is a problem or if there is a more appropriate icon.

**Comment by MathInspector** [comment]
I have not had a chance to thoroughly review Matrix Room yet, but since you recommend it so highly and have been so helpful, as long as there is no exclusivity I am planning to follow your advice and post this project there as well.  I will let you know if I have any questions about Matrix Room after I am more familiar with you, I will ask you.

I am having my lawyer review GPLv3 just to be super safe and make sure I understand exactly what it is all about.  This is the main thing I am waiting on before open sourcing.  I am not planning to start a foundation until the project has a sufficiently large community, but I am hopeful this will happen and the foundation will be a big success.

I want the community to have a lot of input in terms of the rules of the non-profit and how it relates to fundraising.  I don't think it would be fair for me to simply dictate the rules of fundraising for this project, but rather, what would be fair is to let the community decide.

This project belongs to all of us, it's not just mine anymore.

**Comment by MathInspector** [comment]
@Thovthe you said

> It's good that you are so committed. I think a tool to help bring up the next generation of mathematicians from a background different from the traditional training is an excellent tribute to Ramanujan.

I think after ~8 years of math youtube, this is a very special moment in time for the entire math education youtube space.  These students are now ready for much more advanced material.  I am trying to use my youtube channel and this project to take the revolution currently taking place in math education video's to the next level.

**Comment by MathInspector** [comment]
Made this promotional video today, hope you like it!
https://www.youtube.com/watch?v=rN6qRv09M70

**Comment by Thovthe** [comment]
I see you released the project!!!  Hurrah!!!  I'll try to help out where I can, probably mostly in the docs.

**Comment by MathInspector** [comment]
Wondeful!  I have been pretty this week, but will be making a few videos soon to explain the code.

I have 80% finished an entire Sphinx documentation system to be hosted at docs.mathinspector.com, its based on reading docstrings.  I really like this because it's what python uses, so its consistent with the spirit of the project.  Please let me know if you have any suggestions about better frameworks for documentation. 

https://www.sphinx-doc.org/en/master/

Looking forward to working together.  Cheers!
